[package]
name = "organyacat"
description = "Player for Organya music files (Cave Story & friends)"
repository = "https://github.com/crumblingstatue/organyacat"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "0BSD"

[dependencies]
bytemuck = "1.23.2"
